
storages:
  - type: mysql
    params:
      host: "178.104.163.189"
      user: "root"
      password: "cloudsuite#Passw0rd"
      database: "xu_arview"
      table: "operation_log"
  - type: elasticsearch
    params:
      hosts: ["http://localhost:9200"]
      index: "operation-log"