default_storage: mysql
storages:
  mysql:
    enabled: true
    host: 178.104.163.189
    port: 3306
    user: root
    password: cloudsuite#Passw0rd
    db: xu_arview
    table: operation_log
    pool_size: 20
    max_overflow: 5

  elasticsearch:
    enabled: true
    hosts: ["http://178.104.163.189:9200"]
    index: operation-log
    timeout: 30

  redis:
    enabled: false
    host: localhost
    port: 6379
    stream_key: operation_log